apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
spec:
  selector:
    matchLabels:
      name: demo1
  template:
    metadata:
      labels:
        name: demo1
    spec:
      containers:
        - name: app
          image: danielepolencic/troubleshooting
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo1
spec:
  ports:
    - nodePort: 32000
      port: 80
      targetPort: 8080
  selector:
    name: demo1
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo1
spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: demo1
                port:
                  number: 80
            path: /first
            pathType: Prefix
